sudo: required

language: php

php:
  - 7.2

services:
    - docker

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update
  - docker-compose -f docker-compose.testing.yaml up -d

before_script:
  - composer install --no-interaction --no-suggest

script:
  - vendor/bin/phpspec run
  - vendor/bin/codecept run